name: Run Resmi Gazete Bot

on:
  schedule:
    - cron: '0 3 * * *'  # Türkiye saatiyle 06:00 (UTC 03:00)
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Repo'yu klonla
        uses: actions/checkout@v3

      - name: Python kurulumu
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Python kütüphanelerini yükle
        run: |
          pip install selenium beautifulsoup4 requests

      - name: Google Chrome ve uyumlu ChromeDriver kurulumu
        run: |
          sudo apt update
          sudo apt install -y wget unzip
      
          # Chrome kur
          wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo apt install -y ./google-chrome-stable_current_amd64.deb
      
          # Chrome sürümünü al
          CHROME_VERSION=$(google-chrome --version | grep -oP '\d+\.\d+\.\d+' | head -1)
          CHROME_MAJOR=$(echo $CHROME_VERSION | cut -d. -f1)
      
          echo "Chrome major sürüm: $CHROME_MAJOR"
      
          # Uyumlu ChromeDriver sürümünü al
          DRIVER_VERSION=$(wget -qO- "https://chromedriver.storage.googleapis.com/LATEST_RELEASE_$CHROME_MAJOR")
      
          if [ -z "$DRIVER_VERSION" ]; then
            echo "ChromeDriver sürümü alınamadı!"
            exit 1
          fi
      
          echo "İndirilecek ChromeDriver sürümü: $DRIVER_VERSION"
      
          # ChromeDriver indir
          wget -O /tmp/chromedriver.zip "https://chromedriver.storage.googleapis.com/${DRIVER_VERSION}/chromedriver_linux64.zip"
      
          if [ ! -f /tmp/chromedriver.zip ]; then
            echo "ChromeDriver ZIP bulunamadı!"
            exit 1
          fi
      
          unzip /tmp/chromedriver.zip -d /tmp/ || { echo "ZIP açma hatası"; exit 1; }
      
          sudo mv /tmp/chromedriver /usr/local/bin/
          sudo chmod +x /usr/local/bin/chromedriver


      - name: Bot'u çalıştır
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHANNEL_ID: ${{ secrets.TELEGRAM_CHANNEL_ID }}
        run: python main.py
