name: Run Resmi Gazete Bot

on:
  schedule:
    - cron: '0 3 * * *'  # Türkiye saatiyle 06:00 (UTC 03:00)
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Repo'yu klonla
        uses: actions/checkout@v3

      - name: Python kurulumu
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Python kütüphanelerini yükle
        run: |
          pip install selenium beautifulsoup4 requests

      - name: Chrome 136 ve uyumlu ChromeDriver kurulumu
        run: |
          sudo apt update
          sudo apt install -y wget unzip
      
          # Chrome 136 indir
          wget https://dl.google.com/linux/chrome/deb/pool/main/g/google-chrome-stable/google-chrome-stable_136.0.7132.56-1_amd64.deb
          sudo apt install -y ./google-chrome-stable_136.0.7132.56-1_amd64.deb
      
          # ChromeDriver 136 indir
          wget -O /tmp/chromedriver.zip "https://chromedriver.storage.googleapis.com/136.0.7132.56/chromedriver_linux64.zip"
          unzip /tmp/chromedriver.zip -d /tmp/
          sudo mv /tmp/chromedriver /usr/local/bin/
          sudo chmod +x /usr/local/bin/chromedriver


      - name: Bot'u çalıştır
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHANNEL_ID: ${{ secrets.TELEGRAM_CHANNEL_ID }}
        run: python main.py
