name: Run Resmi Gazete Bot

on:
  schedule:
    - cron: '0 3 * * *'  # Türkiye saatiyle 06:00 (UTC 03:00)
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Repo'yu klonla
        uses: actions/checkout@v3

      - name: Python kurulumu
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Python kütüphanelerini yükle
        run: |
          pip install selenium beautifulsoup4 requests

     
      - name: Bot'u çalıştır
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHANNEL_ID: ${{ secrets.TELEGRAM_CHANNEL_ID }}
        run: python main.py
